### PR TITLE
Minimal changes to make it compile

### PR DESCRIPTION
**Pull request by LandRover**
Hey,

Attached some fixes to make the project run and compile without any issues so everyone can run this beautiful project and learn from it.

### CODE REVIEW

**Comment by philipithomas** [comment]
OMG you rock. Thanks so much for doing this 🙏 

I want to spend time confirming that this boots and works ok before merging, so I'll plan to do that by Monday.

**Comment by LandRover** [comment]
I'll try to fix the CI also just for the sake of it a bit later.

**Comment by LandRover** [comment]
Fixed Travis CI.

What to expect?
- Cleanly installs the env from scratch via `vagrant up`.
- vagrant ssh
- cd ~golang/src/v2.staffjoy.com && make dev-build
- The app runs correctly (http://www.staffjoy-v2.local)

Thanks,
Oleg.

**Comment by LandRover** [comment]
Fixed Travis CI.

What to expect?

- Cleanly installs the env from scratch via vagrant up.
- vagrant ssh
- cd ~/golang/src/v2.staffjoy.com && make dev-build
- The app runs correctly (http://www.staffjoy-v2.local)

Thanks,
Oleg.

**Comment by LandRover** [comment]
I've moved it to merge from a local branch so I could more forward with Master for other things.

Thanks,
Oleg.

**Comment by philipithomas** [comment]
@LandRover Thanks so much for doign all of this work. I'm finding myself short on time to review it and merge it. 

What do you think of forking Staffjoy V2, then I can update the official README to say "This repo is deprecated and no longer maintained. For a community-maintained version, see the fork by LandRover here . . ."

**Comment by LandRover** [comment]
Sure, I'm going to keep working on it for educational purposes mainly.

I'm currently forked here: 
Latest - https://github.com/LandRover/StaffjoyV2
Minimal changes to compile - https://github.com/LandRover/StaffjoyV2/tree/minimal-fixes-to-compile

Is it ok?

**Comment by philipithomas** [comment]
Yes! Should I link to your `Latest` or `Minimum Changes To Compile` branch from the README?

Just to give you some insight on merging the pull request: I take this seriously. People use this code in production. I know it's broken in its current state, which is why I greatly appreciate the time that took to fix and improve this. 

By me merging this code, I see it as an endorsement - which means that I tell others that your code is (a) safe, (b) true to the spirit of the original code, and (c) mostly works. I have been extremely busy with my current company [Moonlight](https://www.moonlightwork.com), so I haven't had the time to go through, run your code, make sure it's safe, and provide feedback. 

Because I haven't had time to review this code in a reasonable amount of time, I think the best path forward is for you to make a fork, and maintain it yourself. I'll link to the fork from the README and point new users there, but it's clear to an outsider that it is your code and not mine, which solve my above "endorsement" concerns. 

Thanks so much for working on this! When you're ready, send me an email and I'll tweet out your fork, too!

**Comment by LandRover** [comment]
Ok.

Must say, I totally understand your concerns.

You can go ahead and link to my forked `master` - https://github.com/LandRover/StaffjoyV2
I'll go ahead and update the README as well - For those who still want the original, true to the spirit of the original code to use `Minimal Changes to Compile` branch should be used instead of `master`.

`Minimal Changes to Compile` contains mainly fixing the version numbers to whatever worked 2 years back so Bazel could reproduce the old builds as it was back then.

While on `master` I've upgraded many dependencies to absolute latest, and a list of things I would like complete, including new features.

I'll close the open pull request with an appropriate comment.

Thanks!

**Pull request closed without merging**
